src/Entity/Pret.php
<?php

namespace App\Entity;

use App\Repository\PretRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PretRepository::class)]
class Pret
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $user_name = null;

    #[ORM\Column(length: 255)]
    private ?string $user_mail = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_pret = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_rendu = null;

    #[ORM\Column]
    private ?bool $status = null;

    #[ORM\ManyToOne(inversedBy: 'prets')]
    private ?Materiel $materiel = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function getUserMail(): ?string
    {
        return $this->user_mail;
    }

    public function setUserMail(string $user_mail): self
    {
        $this->user_mail = $user_mail;

        return $this;
    }

    public function getDatePret(): ?\DateTimeInterface
    {
        return $this->date_pret;
    }

    public function setDatePret(\DateTimeInterface $date_pret): self
    {
        $this->date_pret = $date_pret;

        return $this;
    }

    public function getDateRendu(): ?\DateTimeInterface
    {
        return $this->date_rendu;
    }

    public function setDateRendu(\DateTimeInterface $date_rendu): self
    {
        $this->date_rendu = $date_rendu;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getMateriel(): ?Materiel
    {
        return $this->materiel;
    }

    public function setMateriel(?Materiel $materiel): self
    {
        $this->materiel = $materiel;

        return $this;
    }
}

src/Form/PretType.php
<?php

namespace App\Form;

use App\Entity\Pret;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PretType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('user_name')
            ->add('user_mail')
            // ->add('date_pret')
            // ->add('date_rendu')
            // ->add('status')
            ->add('materiel');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pret::class,
        ]);
    }
}

src/Controller/PretController.php
<?php

namespace App\Controller;


use App\Entity\Pret;
use App\Form\PretType;
use App\Repository\PretRepository;
use App\Service\MailerService;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pret')]
class PretController extends AbstractController
{
    #[Route('/', name: 'app_pret_index', methods: ['GET'])]
    public function index(PretRepository $pretRepository): Response
    {
        return $this->render('pret/index.html.twig', [
            'prets' => $pretRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_pret_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PretRepository $pretRepository, MailerService $mailer): Response
    {
        $pret = new Pret();
        $form = $this->createForm(PretType::class, $pret);
        $form->handleRequest($request);
        $interval = new \DateInterval('P15D');
        $date_rendu = new DateTime();
        $date_rendu->add($interval);
        $date_rendu->format('d-m-Y');

        if ($form->isSubmitted() && $form->isValid()) {
            $pret->setDatePret(new DateTime());
            $pret->setDateRendu($date_rendu);
            $pret->setStatus(1);

            if ($pret->getMateriel()->getEnPret() < $pret->getMateriel()->getnombreTotal()) {
                $pret->getMateriel()->setEnPret($pret->getMateriel()->getEnPret() + 1);
            }
            if ($pret->getMateriel()->getEnStock() > 0)
                $pret->getMateriel()->setEnStock($pret->getMateriel()->getEnStock() - 1);
            $pretRepository->save($pret, true);

            $emprunt = $pret->getDatePret()->format('d-m-Y');
            $rendu = $pret->getDateRendu()->format('d-m-Y');
            $matos = $pret->getMateriel()->getNom();
            $destinataire = $pret->getUserMail();
            $objet = 'Pret de matériel';
            $message = "Confirmation de votre emprunt :<br> matériel emprunté : $matos <br> Date de pret : $emprunt <br> Date de retour :  $rendu";

            $mailer->sendEmail($destinataire, $objet, $message);

            return $this->redirectToRoute('app_pret_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pret/new.html.twig', [
            'pret' => $pret,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_pret_show', methods: ['GET'])]
    public function show(Pret $pret): Response
    {
        return $this->render('pret/show.html.twig', [
            'pret' => $pret,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_pret_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Pret $pret, PretRepository $pretRepository): Response
    {
        // $form = $this->createForm(PretType::class, $pret);
        $form = $this->createFormBuilder($pret)
            ->add('user_name')
            ->add('materiel')
            ->add('status')
            ->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($pret->isStatus() == false) {

                if ($pret->getMateriel()->getEnStock() < $pret->getMateriel()->getNombreTotal()) {
                    $pret->getMateriel()->setEnStock($pret->getMateriel()->getEnStock() + 1);
                }

                if ($pret->getMateriel()->getEnPret() > 0) {
                    $pret->getMateriel()->setEnPret($pret->getMateriel()->getEnPret() - 1);
                }
            }

            if ($pret->isStatus() == true) {

                if ($pret->getMateriel()->getEnStock() > 0) {
                    $pret->getMateriel()->setEnStock($pret->getMateriel()->getEnStock() - 1);
                }

                if ($pret->getMateriel()->getEnPret() < $pret->getMateriel()->getNombreTotal()) {
                    $pret->getMateriel()->setEnPret($pret->getMateriel()->getEnPret() + 1);
                }
            }
            $pretRepository->save($pret, true);

            return $this->redirectToRoute('app_pret_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('pret/edit.html.twig', [
            'pret' => $pret,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id?}', name: 'app_pret_delete', methods: ['POST'])]
    public function delete(Request $request, Pret $pret, PretRepository $pretRepository): Response
    {

        if ($this->isCsrfTokenValid('delete' . $pret->getId(), $request->request->get('_token'))) {

            $pretRepository->remove($pret, true);
        }

        if ($pret->getMateriel()->getEnStock() < $pret->getMateriel()->getNombreTotal()) {
            $pret->getMateriel()->setEnStock($pret->getMateriel()->getEnStock() + 1);

            $pretRepository->save($pret, true);
        }

        if ($pret->getMateriel()->getEnPret() > 0) {
            $pret->getMateriel()->setEnPret($pret->getMateriel()->getEnPret() - 1);

            $pretRepository->save($pret, true);
        }

        return $this->redirectToRoute('app_pret_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pret/_delete_form.html.twig
<form method="post" action="{{ path('app_pret_delete', {'id': pret.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pret.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pret/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pret/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pret{% endblock %}

{% block body %}
    <h1>Edit Pret</h1>

    {{ include('pret/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_pret_index') }}">back to list</a>

    {{ include('pret/_delete_form.html.twig') }}
{% endblock %}

templates/pret/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pret index
{% endblock %}

{% block body %}
	<h1>Pret index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Id</th>
				<th>User_name</th>
				<th>Date_pret</th>
				<th>Date_rendu</th>
				<th>En pret</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for pret in prets %}
				<tr>
					<td>{{ pret.id }}</td>
					<td>{{ pret.userName }}</td>
					<td>{{ pret.datePret ? pret.datePret|date('Y-m-d') : '' }}</td>
					<td>{{ pret.dateRendu ? pret.dateRendu|date('Y-m-d') : '' }}</td>
					{% if pret.status == false %}
						<td>Non</td>
					{% else %}
						<td>Oui</td>
					{% endif %}
					<td>
						<a href="{{ path('app_pret_show', {'id': pret.id}) }}">show</a>
						<a href="{{ path('app_pret_edit', {'id': pret.id}) }}">edit</a>
					</td>
				</tr>
			{% else %}
				<tr>
					<td colspan="5">no records found</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>

	<a href="{{ path('app_pret_new') }}">Create new</a>
{% endblock %}

templates/pret/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pret{% endblock %}

{% block body %}
    <h1>Create new Pret</h1>

    {{ include('pret/_form.html.twig') }}

    <a href="{{ path('app_pret_index') }}">back to list</a>
{% endblock %}

templates/pret/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pret
{% endblock %}

{% block body %}
	<h1>Pret</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ pret.id }}</td>
			</tr>
			<tr>
				<th>User_name</th>
				<td>{{ pret.userName }}</td>
			</tr>
			<tr>
				<th>Date_pret</th>
				<td>{{ pret.datePret ? pret.datePret|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Date_rendu</th>
				<td>{{ pret.dateRendu ? pret.dateRendu|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>En pret</th>
				{% if pret.status == false %}
					<td>Non</td>
				{% else %}
					<td>Oui</td>
				{% endif %}
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_pret_index') }}">back to list</a>

	<a href="{{ path('app_pret_edit', {'id': pret.id}) }}">edit</a>

	{{ include('pret/_delete_form.html.twig') }}
{% endblock %}