src/Entity/Materiel.php
<?php

namespace App\Entity;

use App\Repository\MaterielRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MaterielRepository::class)]
class Materiel
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $nombre_total = null;

    #[ORM\Column]
    private ?int $en_stock = null;

    #[ORM\Column(nullable: true)]
    private ?int $en_pret = null;

    #[ORM\OneToMany(mappedBy: 'materiel', targetEntity: Pret::class)]
    private Collection $prets;

    public function __construct()
    {
        $this->prets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNombreTotal(): ?int
    {
        return $this->nombre_total;
    }

    public function setNombreTotal(int $nombre_total): self
    {
        $this->nombre_total = $nombre_total;

        return $this;
    }

    public function getEnStock(): ?int
    {
        return $this->en_stock;
    }

    public function setEnStock(?int $en_stock): self
    {
        $this->en_stock = $en_stock;

        return $this;
    }

    public function getEnPret(): ?int
    {
        return $this->en_pret;
    }

    public function setEnPret(?int $en_pret): self
    {
        $this->en_pret = $en_pret;

        return $this;
    }

    /**
     * @return Collection<int, Pret>
     */
    public function getPrets(): Collection
    {
        return $this->prets;
    }

    public function addPret(Pret $pret): self
    {
        if (!$this->prets->contains($pret)) {
            $this->prets->add($pret);
            $pret->setMateriel($this);
        }

        return $this;
    }

    public function removePret(Pret $pret): self
    {
        if ($this->prets->removeElement($pret)) {
            // set the owning side to null (unless already changed)
            if ($pret->getMateriel() === $this) {
                $pret->setMateriel(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Form/MaterielType.php
<?php

namespace App\Form;

use App\Entity\Materiel;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MaterielType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('nombre_total');
        // ->add('en_stock')
        // ->add('en_pret');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Materiel::class,
        ]);
    }
}

src/Controller/MaterielController.php
<?php

namespace App\Controller;

use App\Entity\Materiel;
use App\Form\MaterielType;
use App\Repository\MaterielRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/materiel')]
class MaterielController extends AbstractController
{
    #[Route('/', name: 'app_materiel_index', methods: ['GET'])]
    public function index(MaterielRepository $materielRepository): Response
    {
        return $this->render('materiel/index.html.twig', [
            'materiels' => $materielRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_materiel_new', methods: ['GET', 'POST'])]
    public function new(Request $request, MaterielRepository $materielRepository): Response
    {
        $materiel = new Materiel();
        $form = $this->createForm(MaterielType::class, $materiel);
        $form->handleRequest($request);
        $materiel->setEnStock($materiel->getNombreTotal());
        $materiel->setEnPret(0);

        if ($form->isSubmitted() && $form->isValid()) {
            $materielRepository->save($materiel, true);

            return $this->redirectToRoute('app_materiel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materiel/new.html.twig', [
            'materiel' => $materiel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_materiel_show', methods: ['GET'])]
    public function show(Materiel $materiel): Response
    {
        return $this->render('materiel/show.html.twig', [
            'materiel' => $materiel,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_materiel_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Materiel $materiel, MaterielRepository $materielRepository): Response
    {
        $form = $this->createForm(MaterielType::class, $materiel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $materielRepository->save($materiel, true);

            return $this->redirectToRoute('app_materiel_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('materiel/edit.html.twig', [
            'materiel' => $materiel,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_materiel_delete', methods: ['POST'])]
    public function delete(Request $request, Materiel $materiel, MaterielRepository $materielRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $materiel->getId(), $request->request->get('_token'))) {
            $materielRepository->remove($materiel, true);
        }

        return $this->redirectToRoute('app_materiel_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/materiel/_delete_form.html.twig
<form method="post" action="{{ path('app_materiel_delete', {'id': materiel.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ materiel.id) }}">
    <button class="btn">Delete</button>
</form>

templates/materiel/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/materiel/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Materiel{% endblock %}

{% block body %}
    <h1>Edit Materiel</h1>

    {{ include('materiel/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_materiel_index') }}">back to list</a>

    {{ include('materiel/_delete_form.html.twig') }}
{% endblock %}

templates/materiel/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Materiel index{% endblock %}

{% block body %}
    <h1>Materiel index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Nombre_total</th>
                <th>En_stock</th>
                <th>En_pret</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for materiel in materiels %}
            <tr>
                <td>{{ materiel.id }}</td>
                <td>{{ materiel.nom }}</td>
                <td>{{ materiel.nombreTotal }}</td>
                <td>{{ materiel.enStock }}</td>
                <td>{{ materiel.enPret }}</td>
                <td>
                    <a href="{{ path('app_materiel_show', {'id': materiel.id}) }}">show</a>
                    <a href="{{ path('app_materiel_edit', {'id': materiel.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_materiel_new') }}">Create new</a>
{% endblock %}

templates/materiel/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Materiel{% endblock %}

{% block body %}
    <h1>Create new Materiel</h1>

    {{ include('materiel/_form.html.twig') }}

    <a href="{{ path('app_materiel_index') }}">back to list</a>
{% endblock %}

templates/materiel/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Materiel{% endblock %}

{% block body %}
    <h1>Materiel</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ materiel.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ materiel.nom }}</td>
            </tr>
            <tr>
                <th>Nombre_total</th>
                <td>{{ materiel.nombreTotal }}</td>
            </tr>
            <tr>
                <th>En_stock</th>
                <td>{{ materiel.enStock }}</td>
            </tr>
            <tr>
                <th>En_pret</th>
                <td>{{ materiel.enPret }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_materiel_index') }}">back to list</a>

    <a href="{{ path('app_materiel_edit', {'id': materiel.id}) }}">edit</a>

    {{ include('materiel/_delete_form.html.twig') }}
{% endblock %}